version: '2'
volumes:
    pid-configuration:

services:
    #temperature-logger:
    #    build: ./temperature-logger
    #    privileged: true
    pid:
        build: ./pid
        privileged: true
        volumes:
            - 'pid-configuration:/config'
