version: '2.1'
volumes:
    pid-configuration:
    pid-logs:
services:
    pid:
        build: ./pid
        privileged: true
        volumes:
            - 'pid-configuration:/config'
            - 'pid-logs:/log'
    api:
        build: ./api
        ports:
            - 9000:9000
        volumes:
            - 'pid-configuration:/config'
            - 'pid-logs:/log'
    #web:
    #    build: ./web
    #    ports:
    #        - 80:3000
    #    volumes:
    #        - 'pid-configuration:/config'