version: '2.1'
volumes:
    pid-configuration:

services:
    pid:
        build: ./pid
        privileged: true
        volumes:
            - 'pid-configuration:/config'
    api:
        build: ./api
        privileged: true
        ports:
            - 80:9000
        volumes:
            - 'pid-configuration:/config'