FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build

RUN pip3 install adafruit-circuitpython-lis3dh
RUN CFLAGS="-fcommon" pip3 install rpi.gpio
RUN pip3 install adafruit-circuitpython-max31855


COPY main.py /usr/src/app/main.py

CMD ["python3","/usr/src/app/main.py"]
