FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build


RUN pip3 install adafruit-circuitpython-lis3dh
RUN CFLAGS="-fcommon" pip3 install rpi.gpio
RUN pip3 install gpiozero
RUN pip3 install adafruit-circuitpython-max31855

COPY PID.py /usr/src/app/PID.py
COPY main.py /usr/src/app/main.py

CMD ["python3","/usr/src/app/main.py"]
